### ISSUE TITLE
React + Typescript problem

### ISSUE THREAD

**Issue by lipedeitos** [ceolter/ag-grid-react-example#13]
Hi, i am having a problem using the ag-grid with my React + typescript + SystemJS (system module) application. I'v tried to install the ag-grid and ag-grid-react with npm and with jspm too...
I install it an then call:
`import { Some } from 'ag-grid-react';`
I'm using VSCode it prints error "[ts] Cannot find module 'ag-grid-react'".

I access the ag-grid-react npm or jspm folder, found the that the AgGridReact.ts refference "../typings/tsd" without the ".d.ts" explicit it was giving me error there too, so i tried to change it and run gulp task again, nothing changed, my component still not finding the import.

This is my typings.json, here i dont find any ag-grid registry:

```
{
  "name": "focco-sys-jspm",
  "dependencies": {
    "react": "registry:npm/react#15.0.1+20160601175240",
    "react-addons-update": "registry:npm/react-addons-update#0.14.0+20160324044346",
    "react-dom": "registry:npm/react-dom#15.0.1+20160705210405",
    "react-router": "registry:npm/react-router#2.4.0+20160811060709"
  },
}
```

When i try to run "typings install --save ag-grid ag-grid-react" i gives me an error and said that i already have the ".d.ts" inside the project folder...

I really don't know how to solve it... someone can help, i can give more info about my project.
Cheers!

**Comment by ceolter** [comment]
please check with this project:
https://github.com/ceolter/ag-grid-ng2-example

it's not React, it's Angular2, however it is using SystemJS and TypeScript, so getting the definition files should be the same.

**Comment by seanlandsman** [comment]
Hi @lipedeitos - I'm closing this as I'd imagine this has been resolved by now.

If this still a problem let me know and I'll try assist you further.

thanks
