### ISSUE TITLE
Where is startEditingCell

### ISSUE THREAD

**Issue by Maikel-mg** [ceolter/ag-grid-react-example#15]
In the examples there is a function startCellEditing used in this way **gridOptions.api.startEditingCell**
¿How can I access to this function in React?

**Comment by seanlandsman** [comment]
If you hold a reference to the gridOptions you'll be able to invoke the method above

ie in your ts file:

    this.gridOptions = {
       ...optional settings

in your react grid declaration:

    <AgGridReact
          gridOptions={this.gridOptions}
          ...other properties

Then in your ts file you could invoke the method above as follows:

    this.gridOptions.api.startEditingCell

**Comment by ceolter** [comment]
alternatively, you can get a reference to the grid's api using the gridReady event, see the section 'Grid API' here: https://www.ag-grid.com/best-react-data-grid/index.php
