### ISSUE TITLE
React CellEditor example on website

### ISSUE THREAD

**Issue by saivikas7875** [ceolter/ag-grid-react-example#16]
I am trying to look at `src-standard` example code here and refer to what's being rendered on the Ag-Grid website - `https://www.ag-grid.com/best-react-data-grid/`. The code and CellEditor documentation mention that the grid is using a React Cell editor for the column `Name`. 

I can't edit any of the names though. The relevant console log information (have other CORS related errors as well) bit is that when I select a `Name` column cell to edit, I get this consoled out,

![capture](https://cloud.githubusercontent.com/assets/4580625/20275669/1283b39c-aa5f-11e6-88ab-a87334e2de63.PNG)

Am I missing something?

**Comment by ceolter** [comment]
the example online is out of date, please check with the github project ag-grid-react-example, i just built it locally and the name column is editable.
