### ISSUE TITLE
ag-grid React Example will not render for IE11

### ISSUE THREAD

**Issue by dhassouni** [ceolter/ag-grid-react-example#17]
The react example used on this page (https://www.ag-grid.com/best-react-data-grid/) does not show up in IE11. It does show up in Edge 14 and all other browsers I've tried. All other examples I've tried, including the main Demo seem to work fine on IE11 (other than known IE-specific performance issues).

**Comment by ceolter** [comment]
works now since last release. i dont know what was wrong, but looks like  the last release fixed it.
