### ISSUE TITLE
Cell Editing onKeyDown

### ISSUE THREAD

**Issue by FrominXu** [ceolter/ag-grid-react-example#18]
I want to stopPropagation when I press the Enter key in a React component  Editor, and refer to the demo:
_MoodEditor.prototype.onKeyDown = function (event) {
    var key = event.which || event.keyCode;
    if (key == 37 ||  // left
        key == 39) {  // right
        this.toggleMood();
        event.stopPropagation();
    }
};_
and 
> The React component will get the 'cellEditor Params' as described above as it's React Props. Therefore you can access all the parameters as React Props.
> 

As the props in React is read-only, what should I do to prevent event propagation? Thks.

**Comment by FrominXu** [comment]
I get it .
key word: 'cellEditor Params'.

**Comment by sjain-mi9** [comment]
Not sure how would you use that in cellEditorParams. Can you please provide an example.

**Comment by FrominXu** [comment]
@sjain-mi9 
I found the onKeyDown property is only useful when the cell is popup. so the issue is still not closed.

**Comment by sjain-mi9** [comment]
For our own cell editor wrapper, this method worked for me:

componentDidMount() {
		// Preventing the default behavior of left right and enter key.
		this.divRef.addEventListener('keydown', (e) => {
			const keyCode = ('which' in event) ? event.which : event.keyCode;
			if (keyCode === 37 || // left
				keyCode === 39 || // right
				keyCode === 13) { // enter
				e.stopPropagation();
			}
		});
	}
Within your component div add ref={(ref) => { this.divRef = ref; }} and tabIndex="0"
