### ISSUE TITLE
Request: add example for how to use `onKeyDown` callback noted in docs

### ISSUE THREAD

**Issue by buddyp450** [ceolter/ag-grid-react-example#19]
The [online docs](https://www.ag-grid.com/javascript-grid-cell-editing/) references a callback 'onKeyDown' that can be used to prevent keyboard event propagation. If it's true to do this to prevent the default behavior of the 'Enter' key to begin editing a cell or stop editing a cell, could you please incorporate this into your awesome examples? :)

**Comment by seanlandsman** [comment]
Hi - I assume that you've managed to work around this (perhaps by using listeners?) given the age of the issue. As such I'm going to close this - please let us know if this is not the case and I can reopen this and we can try assist you further.  Thanks
