### ISSUE TITLE
Proficiency column in example is blank

### ISSUE THREAD

**Issue by dhassouni** [ceolter/ag-grid-react-example#20]
Something isn't functioning as intended in this example with the cell renderer. Not urgent, but figured I'd bring it to your attention.

![screen shot 2016-12-27 at 1 10 54 pm](https://cloud.githubusercontent.com/assets/3877429/21507504/19634f08-cc36-11e6-84a4-fd7f71a044ed.png)

**Comment by ceolter** [comment]
fixed. thanks for raising :)
