### ISSUE TITLE
getting an error on running a fresh install

### ISSUE THREAD

**Issue by stevewirts** [ceolter/ag-grid-react-example#25]
Hi,
when I do a simple npm install, then npm run large, I get the following output...

> ag-grid-react-example@10.0.0 large c:\Work\Projects\ag-grid-react-example
> webpack-dev-server --config webpack.config.large.js --progress --colors --hot --inline

 70% 1/1 build moduleshttp://localhost:8080/
webpack result is served from /
content is served from c:\Work\Projects\ag-grid-react-example
Hash: 44fa37be77c0890c2c74
Version: webpack 1.12.11
Time: 279ms
         Asset     Size  Chunks             Chunk Names
dist/bundle.js  24.5 kB       0  [emitted]  main
chunk    {0} dist/bundle.js (main) 2.72 kB [rendered]
    [0] multi main 52 bytes {0} [built] [2 errors]
    [1] (webpack)-dev-server/client?http://localhost:8080 2.67 kB {0} [built] [3 errors]

ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ multi main

ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ multi main

ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ (webpack)-dev-server/client?http://localhost:8080 1:10-24

ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ (webpack)-dev-server/client?http://localhost:8080 3:16-37

ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ (webpack)-dev-server/client?http://localhost:8080 2:13-37
webpack: Failed to compile.

**Comment by stevewirts** [comment]
solved it......
In in package.json I changed
  "devDependencies": {
    "babel-core": "6.0.0",
    "babel-loader": "6.2.1",
    "babel-preset-es2015": "6.3.13",
    "babel-preset-react": "6.3.13",
    "babel-preset-stage-1": "6.24.1",
    "css-loader": "0.23.1",
    "style-loader": "0.13.0",
    "webpack": "1.12.11",
    "webpack-dev-server": "1.14.1"
  },
to this
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-loader": "^6.2.1",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-1": "^6.24.1",
    "css-loader": "0.23.1",
    "style-loader": "0.13.0",
    "webpack": "1.12.11",
    "webpack-dev-server": "1.14.1"
  },

**Comment by sairamkrish** [comment]
faced same issue. Thanks @stevewirts - your answer was helpful

**Comment by seanlandsman** [comment]
You caught the examples repo in a state of flux - the next checkin I make today will solve this too

Sorry for the hassle

**Comment by shrinandhini2801** [comment]
Still i face the same problem
