### ISSUE TITLE
Throwing ERROR in Cannot find module 'babel-runtime/helpers/interop-require'

### ISSUE THREAD

**Issue by shrinandhini2801** [ceolter/ag-grid-react-example#26]
I am not able to compile the code. Wep pack keeps on throwing error like below,

ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ multi main

ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ multi main

ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ (webpack)-dev-server/client?http://localhost:8080 1:10-24

ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ (webpack)-dev-server/client?http://localhost:8080 3:16-37

ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ (webpack)-dev-server/client?http://localhost:8080 2:13-37

**Comment by bryankennedy** [comment]
I was able to get the example to compile by removing the version number requirement for babel-core in `package.json`

        "babel-core": "",

I think something in there is still depending on an old version of babel, and this lets it find what it needs.

**Comment by seanlandsman** [comment]
Hi

Should build and run fine now

thanks
