### ISSUE TITLE
Error when sorting in Rich Grid Example

### ISSUE THREAD

**Issue by tylermassey** [ceolter/ag-grid-react-example#28]
This error is given when trying to sort a column in the Rich Grid Example

```
react-examples.js:9430 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the SortableHeaderComponent component.
```

The error is being thrown in the [`onSortChanged` method of the custom header component](https://github.com/ceolter/ag-grid-react-example/blob/master/src/richGridExample/SortableHeaderComponent.jsx#L54).

**Comment by tylermassey** [comment]
One fix is to simply remove the event listener when the component unmounts. [See this StackOverflow answer](https://stackoverflow.com/a/35345455).

To do this successfully, you need to bind `this.onSortChanged` before adding the event listener like so

```
constructor(props) {
    super(props);

    this.onSortChanged = this.onSortChanged.bind(this);
    this.props.column.addEventListener('sortChanged', this.onSortChanged.bind(this));

    //The state of this component contains the current sort state of this column
    //The possible values are: 'asc', 'desc' and ''
    this.state = {
        sorted: ''
    }
}

componentWillUnmount() {
    this.props.column.removeEventListener('sortChanged', this.onSortChanged);
}
```

To avoid having to bind the sort method, use an arrow function when declaring `onSortChanged` like so:

```
onSortChanged = () => {
    if (this.props.column.isSortAscending()) {
        this.setState({
            sorted: 'asc'
        })
    } else if (this.props.column.isSortDescending()) {
        this.setState({
            sorted: 'desc'
        })
    } else {
        this.setState({
            sorted: ''
        })
    }
};
```

**Comment by seanlandsman** [comment]
thanks - I'll look and putting this fix in early next week

**Comment by ralphsmith80** [comment]
@tylermassey nice find, I was just refactoring some older code and ran into this. Saved me some time.

**Comment by seanlandsman** [comment]
@tylermassey finally applied this - apologies for the delay and thanks for reporting
