### ISSUE TITLE
Port to React v15

### ISSUE THREAD

**Issue by DOMZE** [ceolter/ag-grid-react-example#6]
Any plan on porting this to React 15?
If so what is your ETA?

**Comment by ceolter** [comment]
no plan to do so. why, does it not work with 15? has 15 got breaking changes?

**Comment by DOMZE** [comment]
A part from optimization improvements (speed), this is what can be found on their blog:

**Upgrade Guide**
As usual with major releases, React 15 will remove support for some of the patterns deprecated nine months ago in React 0.14. We know changes can be painful (the Facebook codebase has over 20,000 React components, and that’s not even counting React Native), so we always try to make changes gradually in order to minimize the pain.

If your code is free of warnings when running under React 0.14, upgrading should be easy. The bulk of changes in this release are actually behind the scenes, impacting the way that React interacts with the DOM. The other substantial change is that React now supports the full range of SVG elements and attributes. Beyond that we have a large number of incremental improvements and additional warnings aimed to aid developers. We’ve also laid some groundwork in the core to bring you some new capabilities in future releases.

See the changelog below for more details.

[React v-15](https://facebook.github.io/react/blog/2016/04/07/react-v15.html)
