### ISSUE TITLE
can headerCellRenderer using reactCellRendererFactory?

### ISSUE THREAD

**Issue by hank7444** [ceolter/ag-grid-react-example#7]
I tried to add checkbox on header for check/cancel all

but I got a err msg:

```
invariant.js:38Uncaught Invariant Violation: _registerComponent(...): Target container is not a DOM element.
```

I try return html directly, but I can't binding the event which create in react..

![image](https://cloud.githubusercontent.com/assets/4727090/15275022/5faead8a-1af3-11e6-92b3-6f120b73d92f.png)

Have any Idea?

**Comment by nemish** [comment]
+1

**Comment by elhay-av** [comment]
+1

my solution:

```javaScript
function reactHeaderRendererFactory(reactComponent) {
  return function (params) {
    var eCell = document.createElement('span');

    ReactDOM.render(reactComponent({params}), eCell);

    return eCell;
  };
}
```

**Comment by ceolter** [comment]
not provided out of the box (yet). i intent to cover better support for Reach (and Angular 2) in custom components in a release that will be available in approx 2 months from now.

**Comment by hank7444** [comment]
here is my solution

```
{
        headerName: 'checkbox',
        field: 'chck',
        width: 30,
        minWidth: 30,
        maxWidth: 30,
        headerCellTemplate: this._selectAllCheckboxHeaderCellRendererFunc,
        suppressSorting: true,
        suppressMovable: true,
        suppressResize: true,
        cellRenderer: reactCellRendererFactory(Checkbox),
}
 _selectAllCheckboxHeaderCellRendererFunc() {
    const input = this.checkAllInput;
    const icon = this.checkAllIcon;

    const header = document.createElement('div');

    input.setAttribute('type', 'checkbox');
    input.style.display = 'none';

    icon.addEventListener('click', () => {
      this._handleOnSelectAll(!input.checked);
    });

    header.appendChild(input);
    header.appendChild(icon);
    return header;
  }
```

**Comment by marc314** [comment]
Solution posted by @elhay-av works, however when I drag the column the values are gone and the headers appear blank. Any advice?

**Comment by marc314** [comment]
Never mind.. 
``  onColumnMoved = event => this.api.refreshHeader() ``

**Comment by seanlandsman** [comment]
Hi - this should now be resolved as we now support header components. Please let us know if this is not the case.  Thanks
